# Generated by Django 3.1.1 on 2021-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=5)),
                ('like_username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('post_text', models.CharField(max_length=100)),
                ('post_img', models.CharField(max_length=50)),
            ],
        ),
    ]
